//line lang.y:2

// THIS FILE IS AUTOGENERATED, DO NOT EDIT!
package brb

import __yyfmt__ "fmt"

//line lang.y:3
import (
	"math/big"
)

//line lang.y:11
type yySymType struct {
	yys      int
	lval     *big.Rat
	variable string
}

const NUM = 57346
const INV = 57347
const VAR = 57348
const NEG = 57349

var yyToknames = []string{
	"NUM",
	"INV",
	"VAR",
	"'-'",
	"'+'",
	"'*'",
	"'/'",
	"NEG",
}
var yyStatenames = []string{}

const yyEofCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

//line lang.y:55

//line yacctab:1
var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyNprod = 14
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 44

var yyAct = []int{

	3, 16, 10, 9, 11, 12, 14, 2, 17, 25,
	18, 19, 20, 21, 22, 13, 1, 24, 10, 9,
	11, 12, 11, 12, 0, 23, 8, 6, 15, 7,
	8, 6, 4, 7, 0, 5, 0, 0, 0, 5,
	10, 9, 11, 12,
}
var yyPact = []int{

	-1000, 26, -1000, 33, 3, 22, -12, 22, -1000, 22,
	22, 22, 22, 22, 11, -1000, 22, -1000, 13, 13,
	-1000, -1000, 33, -1000, -5, -1000,
}
var yyPgo = []int{

	0, 0, 16, 7,
}
var yyR1 = []int{

	0, 2, 2, 3, 3, 1, 1, 1, 1, 1,
	1, 1, 1, 1,
}
var yyR2 = []int{

	0, 0, 2, 1, 3, 3, 3, 3, 3, 3,
	4, 2, 1, 1,
}
var yyChk = []int{

	-1000, -2, -3, -1, 6, 13, 5, 7, 4, 8,
	7, 9, 10, 12, -1, 6, 13, -1, -1, -1,
	-1, -1, -1, 14, -1, 14,
}
var yyDef = []int{

	1, -2, 2, 3, 13, 0, 0, 0, 12, 0,
	0, 0, 0, 0, 0, 13, 0, 11, 6, 7,
	8, 9, 4, 5, 0, 10,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	13, 14, 9, 8, 3, 7, 3, 10, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 12,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 11,
}
var yyTok3 = []int{
	0,
}

//line yaccpar:1

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	// 4 is TOKSTART above
	if c >= 4 && c-4 < len(yyToknames) {
		if yyToknames[c-4] != "" {
			return yyToknames[c-4]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(c), uint(char))
	}
	return c
}

func yyParse(yylex yyLexer) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		//line lang.y:33
		{
			yylex.(*yylexer).result = yyS[yypt-0].lval
		}
	case 4:
		//line lang.y:34
		{
			yylex.(*yylexer).variables[yyS[yypt-2].variable] = yyS[yypt-0].lval
		}
	case 5:
		//line lang.y:37
		{
			yyVAL.lval = new(big.Rat).Set(yyS[yypt-1].lval)
		}
	case 6:
		//line lang.y:38
		{
			yyVAL.lval = new(big.Rat).Add(yyS[yypt-2].lval, yyS[yypt-0].lval)
		}
	case 7:
		//line lang.y:39
		{
			yyVAL.lval = new(big.Rat).Sub(yyS[yypt-2].lval, yyS[yypt-0].lval)
		}
	case 8:
		//line lang.y:40
		{
			yyVAL.lval = new(big.Rat).Mul(yyS[yypt-2].lval, yyS[yypt-0].lval)
		}
	case 9:
		//line lang.y:41
		{
			yyVAL.lval = new(big.Rat).Quo(yyS[yypt-2].lval, yyS[yypt-0].lval)
		}
	case 10:
		//line lang.y:42
		{
			yyVAL.lval = new(big.Rat).Inv(yyS[yypt-1].lval)
		}
	case 11:
		//line lang.y:43
		{
			yyVAL.lval = new(big.Rat).Neg(yyS[yypt-0].lval)
		}
	case 12:
		//line lang.y:44
		{
			yyVAL.lval = new(big.Rat).Set(yyS[yypt-0].lval)
		}
	case 13:
		//line lang.y:45
		{
			val := yylex.(*yylexer).getVar(yyS[yypt-0].variable)
			if val == nil {
				yylex.(*yylexer).Errorf("unknown variable: %v", yyS[yypt-0].variable)
				goto ret1
			}
			yyVAL.lval = val
		}
	}
	goto yystack /* stack new state and value */
}
